spring:
  profiles.active: ${SPRING_ACTIVE_PROFILE}

---

spring:
  config.activate.on-profile: dev
  h2.console.enabled: true
  datasource.url: jdbc:h2:mem:/.gites
  jpa:
    hibernate.ddl-auto: create

dataLoader:
  populate: true
  source: file
  path: src/main/resources/data.json

---

spring:
  config.activate.on-profile: heroku-postgres
  datasource:
    url: jdbc:postgresql://ec2-79-125-30-28.eu-west-1.compute.amazonaws.com:5432/d1svkiflvvv87n
    username: faemqiltwjxspm
    password: 08f11afb1a387c3b09ba5895c2dde6b5e00676cc6ad23a7dd66d74f48111aae8
    driverClassName: org.postgresql.Driver
    initialization-mode: never
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  config.activate.on-profile: heroku-h2
  h2.console.enabled: true
  datasource.url: jdbc:h2:mem:/.gites
  jpa:
    hibernate.ddl-auto: create

dataLoader:
  populate: true
  source: url
  path: https://7521680b-4b85-40f2-bf3f-dd2ac91f400f.usrfiles.com/ugd/752168_405bc89b17994a54a75bd46bb746e8fc.txt

---